# https://taskfile.dev/
version: '3'

vars:
  BINARY: tinytexonfly
  GO_PACKAGES:
    sh: go list ./...

tasks:
  default:
    cmds:
      - task: run

  run:
    desc: run this
    cmds:
      - task: build
      - ./BINARY{{.EXE_EXT}}
    vars:
      EXE_EXT: '{{if eq OS "windows"}}.exe{{else}}{{end}}'

  build:
    desc: build only
    cmds:
      - task: gen
      - task: fmt
      - go build

  fmt:
    desc: go fmt
    cmds:
      - go fmt

  gen:
    desc: go generate
    cmds:
      - go generate

  mod:
    desc: Downloads and tidy Go modules
    cmds:
      - go mod download
      - go mod tidy

  lint:
    desc: golangci-lint
    cmds:
      - task: fmt
      - golangci-lint run

  test:
    desc: Runs test suite
    cmds:
      - task: fmt
      - go test {{catLines .GO_PACKAGES}}

  ci:
    desc: run CI things
    cmds:
      - task: lint
      - task: test

  packages:
    cmds:
      - echo '{{.GO_PACKAGES}}'
    silent: true
